frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Auth;
use common\models\Calendar;
use common\models\Profile;
use frontend\models\ContactForm;
use frontend\models\UserSettingForm;
use frontend\models\UserSignUpForm;
use frontend\models\User;
use Yii;
use frontend\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\CalendarForm;
use yii\base\InvalidParamException;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\ServerErrorHttpException;
use yii\widgets\ActiveForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'sign-up','login','request-password-reset','index'],
                'rules' => [
                    [
                        'actions' => ['sign-up','login','request-password-reset'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout','index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'onAuthSuccess'],
                'successUrl' => Url::to(['site/index']),
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionHoliday()
    {
        /**@var $user User*/
        $user = Yii::$app->user->identity;

        if($user->role < User::ROLE_ADMIN){
            throw new ForbiddenHttpException();
        }

        $model = new CalendarForm(['scenario'=>'holiday']);
        $model->id = Yii::$app->request->get('edit');

        if($model->id){
            /**@var $calendar Calendar*/
            $calendar = Calendar::findOne(['id'=>$model->id]);
            if(!$calendar){
                throw new NotFoundHttpException();
            }
            $model->attributes = $calendar->attributes;
            $model->start = (new \DateTime($model->start))->format('d-m-Y');
            $model->end = (new \DateTime($model->end))->format('d-m-Y');
        }

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->save()) {
            Yii::$app->getSession()->setFlash('success', $model->id?
                'Your changes are successfully saved':'New holiday has been successfully added');
            return Yii::$app->getResponse()->redirect(['site/holidays']);
        }else if (Yii::$app->request->isPost){
            Yii::$app->getSession()->setFlash('error',  $model->id?
                'We were unable to save changes':'We were unable to add the new holiday');
        }
        return $this->render('holiday',['model'=>$model]);
    }

    /**
     * @param $client \yii\authclient\ClientInterface
     * @return Response | null;
     */
    public function onAuthSuccess($client)
    {
        /**@var $auth \common\models\Auth */

        $attributes = Auth::parseAttributes($client);
        $auth = Auth::find()->where([
            'source' => $client->getId(),
            'source_id' => $attributes['id'],
        ])->one();

        if (Yii::$app->user->isGuest) {
            if ($auth) { // login
                $user = $auth->user;
                Yii::$app->user->login($user);
            } else { // signup
                if (isset($attributes['email'])  && User::find()->where(['email' => $attributes['email']])->exists()) {
                    Yii::$app->getSession()->setFlash('error',
                        Yii::t('app', "User with the same email as in {client} account already exists but isn't linked to it. Login using email first to link it.", ['client' => $client->getTitle()])
                    );
                } else {
                    $attributes['sourceName']   = $client->getId();
                    $attributes['sourceId']     = $attributes['id'];
                    $response = Yii::$app->getResponse();
                    $response->content = Yii::$app->getView()->renderFile(Yii::getAlias('@app/views/site/auth/popup.php'),['attributes'=>$attributes]);
                    return $response;
                }
            }
        } else { // user already logged in
            if (!$auth) { // add auth provider
                $auth = new Auth([
                    'user_id' => Yii::$app->user->id,
                    'source' => $client->getId(),
                    'source_id' => $attributes['id'],
                ]);
                $auth->save();
            }
        }

        return null;

    }

    public function actionLogin()
    {
        $this->layout = 'auth';
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack(['site/index']);
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return Yii::$app->getResponse()->redirect(['site/login']);
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionSignUp()
    {
        $this->layout = 'auth';
        $model = new UserSignUpForm();
        $model->gender = Profile::GENDER_MALE;
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signUp()) {
                if (Yii::$app->user->login($user)) {
                    return $this->goHome();

                }else{
                    return Yii::$app->getResponse()->redirect(['site/login']);
                }
            }
        }

        return $this->render('sign_up', [
            'model' => $model,
        ]);
    }

    public function actionRequestPasswordReset()
    {
        $this->layout = 'auth';
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');
                $model->email = null;

            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword()
    {
        $token = Yii::$app->request->get('token');
        $this->layout = 'auth';
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionVacation()
    {
        /**@var $user User*/
        $user = Yii::$app->user->identity;

        if($user->role <= User::ROLE_USER){
            throw new ForbiddenHttpException();
        }

        $model = new CalendarForm(['scenario'=>'vacation']);
        $model->id = Yii::$app->request->get('edit');


        if($model->id){
            /**@var $calendar Calendar*/
            $calendar = Calendar::findOne(['id'=>$model->id]);
            if(!$calendar){
                throw new NotFoundHttpException();
            }

            if($user->role < User::ROLE_PM){
                throw new ForbiddenHttpException();
            }

            $model->attributes = $calendar->attributes;
            $model->start = (new \DateTime($model->start))->format('d-m-Y');

frontend/controllers/UserController.php
<?php
/**
 * Created by PhpStorm.
 * User: buba
 * Date: 27.04.15
 * Time: 20:19
 */

namespace frontend\controllers;


use frontend\models\User;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class UserController extends Controller{


    /**
     * @inheritdoc
     */
    public function init()
    {
        $this->layout = 'main';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],

                ],
            ],
        ];
    }



    public function actionProfile(){

        if($user = User::findByUsername(\Yii::$app->request->get('username'))){
            return $this->render('profile',['user'=>$user]);
        }else{
            throw new NotFoundHttpException();
        }

    }

    public function actionConfirmEmailRequest(){
        /* @var $user \frontend\models\User */
        $user = \Yii::$app->user->identity;
        if($user->sendEmailConfirmation()){
            \Yii::$app->getSession()->setFlash('success', 'Please check your email for confirmation');
        }else{
            \Yii::$app->getSession()->setFlash('danger', 'There was be an error when sending confirmation token');
        }
        return  $this->redirect(\Yii::$app->request->referrer?:'profile');

    }

    public function actionConfirmEmail($token)
    {
        try {
            $user = User::findByEmailConfirmationToken($token);
            if($user){
                $user->removeEmailConfirmationToken();
                $user->save();
                \Yii::$app->getSession()->setFlash('success', 'You successfully confirmed your email address');
                return \Yii::$app->getResponse()->redirect(Url::to(['profile']));
            }else{
                throw new Exception('Wrong email confirmation token');
            }

        } catch (Exception $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
    }
}

frontend/views/layouts/_config.php
<div id="config-tool" class="closed">
    <a id="config-tool-cog">
        <i class="fa fa-cog"></i>
    </a>

    <div id="config-tool-options">
        <h4>Layout Options</h4>
        <ul>
            <li>
                <div class="checkbox-nice">
                    <input type="checkbox" id="config-fixed-header" />
                    <label for="config-fixed-header">
                        Fixed Header
                    </label>
                </div>
            </li>
            <li>
                <div class="checkbox-nice">
                    <input type="checkbox" id="config-fixed-sidebar" />
                    <label for="config-fixed-sidebar">
                        Fixed Left Menu
                    </label>
                </div>
            </li>
            <li>
                <div class="checkbox-nice">
                    <input type="checkbox" id="config-fixed-footer" />
                    <label for="config-fixed-footer">
                        Fixed Footer
                    </label>
                </div>
            </li>
            <li>
                <div class="checkbox-nice">
                    <input type="checkbox" id="config-boxed-layout" />
                    <label for="config-boxed-layout">
                        Boxed Layout
                    </label>
                </div>
            </li>
            <li>
                <div class="checkbox-nice">
                    <input type="checkbox" id="config-rtl-layout" />
                    <label for="config-rtl-layout">
                        Right-to-Left
                    </label>
                </div>
            </li>
        </ul>
        <br/>
        <h4>Skin Color</h4>
        <ul id="skin-colors" class="clearfix">
            <li>
                <a class="skin-changer" data-skin="" data-toggle="tooltip" title="Default" style="background-color: #34495e;">
                </a>
            </li>
            <li>
                <a class="skin-changer" data-skin="theme-white" data-toggle="tooltip" title="White/Green" style="background-color: #2ecc71;">
                </a>
            </li>
            <li>
                <a class="skin-changer blue-gradient" data-skin="theme-blue-gradient" data-toggle="tooltip" title="Gradient">
                </a>
            </li>
            <li>
                <a class="skin-changer" data-skin="theme-turquoise" data-toggle="tooltip" title="Green Sea" style="background-color: #1abc9c;">
                </a>
            </li>
            <li>
                <a class="skin-changer" data-skin="theme-amethyst" data-toggle="tooltip" title="Amethyst" style="background-color: #9b59b6;">
                </a>
            </li>
            <li>
                <a class="skin-changer" data-skin="theme-blue" data-toggle="tooltip" title="Blue" style="background-color: #2980b9;">
                </a>
            </li>
            <li>
                <a class="skin-changer" data-skin="theme-red" data-toggle="tooltip" title="Red" style="background-color: #e74c3c;">
                </a>
            </li>
            <li>
                <a class="skin-changer" data-skin="theme-whbl" data-toggle="tooltip" title="White/Blue" style="background-color: #3498db;">
                </a>
            </li>
        </ul>
    </div>
</div>

frontend/views/layouts/_footer.php
<footer id="footer-bar" class="row <?=isset($this->params['layout']) && $this->params['layout']=='messages'?'hidden-md hidden-lg':''?>">
    <p id="footer-copyright" class="col-xs-12">
        &copy; <?=date('Y');?> <a href="http://www.bigdropinc.com/" target="_blank">Bigdropinc</a>. Powered by BIGDROP.
    </p>
</footer>

frontend/views/layouts/_header.php
<?php
/**@var $user frontend\models\User*/
$user = Yii::$app->user->getIdentity();
?>
<header class="navbar" id="header-navbar">
    <div class="container">
        <a href="/admin" id="logo" class="navbar-brand">
            <img src="/img/logo.png" alt="" class="normal-logo logo-white"/>
            <img src="/img/logo-black.png" alt="" class="normal-logo logo-black"/>
            <img src="/img/logo-small.png" alt="" class="small-logo hidden-xs hidden-sm hidden"/>
        </a>

        <div class="clearfix">
            <button class="navbar-toggle" data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="fa fa-bars"></span>
            </button>

            <div class="nav-no-collapse navbar-left pull-left hidden-sm hidden-xs">
                <ul class="nav navbar-nav pull-left">
                    <li>
                        <a class="btn" id="make-small-nav">
                            <i class="fa fa-bars"></i>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="nav-no-collapse pull-right" id="header-nav">
                <ul class="nav navbar-nav pull-right">
                    <li class="dropdown profile-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="hidden-xs"><?=$user->username?></span> <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?= \yii\helpers\Url::to(['user/profile','username'=>$user->username])?>"><i class="fa fa-user"></i>Profile</a></li>
                            <li><a href="#change-password" class="md-trigger" data-modal="modal-1"><i class="fa fa-refresh"></i>Change password</a></li>
                            <li><a href="<?= \yii\helpers\Url::to(['logout'])?>"><i class="fa fa-power-off"></i>Logout</a></li>
                        </ul>
                    </li>
                    <li class="hidden-xxs">
                        <a href="<?= \yii\helpers\Url::to(['logout'])?>" class="btn">
                            <i class="fa fa-power-off"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>

frontend/views/layouts/_main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\TimelineAsset;
use frontend\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

TimelineAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>
    <div class="wrap">
        <?php
            NavBar::begin([
                'brandLabel' => 'My Company',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            $menuItems = [
                ['label' => 'Home', 'url' => ['/site/index']],
                ['label' => 'About', 'url' => ['/site/about']],
                ['label' => 'Contact', 'url' => ['/site/contact']],
            ];
            if (Yii::$app->user->isGuest) {
                $menuItems[] = ['label' => 'Signup', 'url' => ['/site/sign-up']];
                $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
            } else {
                $menuItems[] = [
                    'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                    'url' => ['/site/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ];
            }
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $menuItems,
            ]);
            NavBar::end();
        ?>

        <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>
        <p class="pull-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/_nav.php
<div id="nav-col">
<section id="col-left" class="col-left-nano">
<div id="col-left-inner" class="col-left-nano-content">
<div class="collapse navbar-collapse navbar-ex1-collapse" id="sidebar-nav">
<ul class="nav nav-pills nav-stacked">
<li class="<?=Yii::$app->controller->action->getUniqueId()=='site/index'?'active':''?>">
    <a href="<?=\yii\helpers\Url::base()?>/" >
        <i class="fa fa-dashboard"></i>
        <span>Dashboard</span>
    </a>
</li>
<li class="<?=in_array(Yii::$app->controller->action->getUniqueId(),['site/admins','site/users'])?'open active':'';?>">
    <a href="#" class="dropdown-toggle">
        <i class="fa fa-users"></i>
        <span>Users</span>
        <i class="fa fa-chevron-circle-right drop-icon"></i>
    </a>
    <ul class="submenu">
        <li>
            <a href="<?=\yii\helpers\Url::to(['site/admins'])?>" class="<?=Yii::$app->controller->action->getUniqueId()=='site/admins'?'active':''?>">
                Administrators
            </a>
        </li>
        <li>
            <a href="<?=\yii\helpers\Url::to(['site/users'])?>" class="<?=Yii::$app->controller->action->getUniqueId()=='site/users'?'active':''?>">
                Members
            </a>
        </li>
    </ul>
</li>
    <li class="<?=Yii::$app->controller->action->getUniqueId()=='site/vacations'?'active':''?>">
        <a href="<?=\yii\helpers\Url::to(['site/vacations'])?>" >
            <i class="fa fa-plane"></i>
            <span>Vacations</span>
        </a>
    </li>
    <li class="<?=Yii::$app->controller->action->getUniqueId()=='site/holidays'?'active':''?>">
        <a href="<?=\yii\helpers\Url::to(['site/holidays'])?>" >
            <i class="fa fa-h-square"></i>
            <span>Holidays</span>
        </a>
    </li>
</ul>
</div>
</div>
</section>
</div>

frontend/views/layouts/auth.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\TimelineAsset;
use frontend\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <style>
        #login-box .btn-google {
            text-transform: none;
            font-size: 1em;
            margin-bottom: 10px;
        }
        .btn-google:hover {
            background-color: #a33a2b !important;
            border-color: #501e13 !important;
        }

        .btn-google {
            background-color:#DF4A32 !important;
            border-color:#6C241B  !important;
        }
    </style>
</head>
<body>
<?php $this->beginBody() ?>
<body id="login-page">
    <div class="container">
        <?=$content?>
    </div>
    <div id="config-tool" class="closed">
        <a id="config-tool-cog">
            <i class="fa fa-cog"></i>
        </a>

        <div id="config-tool-options">
            <h4>Layout Options</h4>
            <ul>
                <li>
                    <div class="checkbox-nice">
                        <input type="checkbox" id="config-fixed-header" />
                        <label for="config-fixed-header">
                            Fixed Header
                        </label>
                    </div>
                </li>
                <li>
                    <div class="checkbox-nice">
                        <input type="checkbox" id="config-fixed-sidebar" />
                        <label for="config-fixed-sidebar">
                            Fixed Left Menu
                        </label>
                    </div>
                </li>
                <li>
                    <div class="checkbox-nice">
                        <input type="checkbox" id="config-fixed-footer" />
                        <label for="config-fixed-footer">
                            Fixed Footer
                        </label>
                    </div>
                </li>
                <li>
                    <div class="checkbox-nice">
                        <input type="checkbox" id="config-boxed-layout" />
                        <label for="config-boxed-layout">
                            Boxed Layout
                        </label>
                    </div>
                </li>
                <li>
                    <div class="checkbox-nice">
                        <input type="checkbox" id="config-rtl-layout" />
                        <label for="config-rtl-layout">
                            Right-to-Left
                        </label>
                    </div>
                </li>
            </ul>
            <br/>
            <h4>Skin Color</h4>
            <ul id="skin-colors" class="clearfix">
                <li>
                    <a class="skin-changer" data-skin="" data-toggle="tooltip" title="Default" style="background-color: #34495e;">
                    </a>
                </li>
                <li>
                    <a class="skin-changer" data-skin="theme-white" data-toggle="tooltip" title="White/Green" style="background-color: #2ecc71;">
                    </a>
                </li>
                <li>
                    <a class="skin-changer blue-gradient" data-skin="theme-blue-gradient" data-toggle="tooltip" title="Gradient">
                    </a>
                </li>
                <li>
                    <a class="skin-changer" data-skin="theme-turquoise" data-toggle="tooltip" title="Green Sea" style="background-color: #1abc9c;">
                    </a>
                </li>
                <li>
                    <a class="skin-changer" data-skin="theme-amethyst" data-toggle="tooltip" title="Amethyst" style="background-color: #9b59b6;">
                    </a>
                </li>
                <li>
                    <a class="skin-changer" data-skin="theme-blue" data-toggle="tooltip" title="Blue" style="background-color: #2980b9;">
                    </a>
                </li>
                <li>
                    <a class="skin-changer" data-skin="theme-red" data-toggle="tooltip" title="Red" style="background-color: #e74c3c;">
                    </a>
                </li>
                <li>
                    <a class="skin-changer" data-skin="theme-whbl" data-toggle="tooltip" title="White/Blue" style="background-color: #3498db;">
                    </a>
                </li>
            </ul>
        </div>
    </div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/error.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;

/* @var $this \yii\web\View */
/* @var $content string */

//AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <!-- bootstrap -->
    <link rel="stylesheet" type="text/css" href="<?=Url::base()?>/css/bootstrap/bootstrap.min.css" />

    <!-- RTL support - for demo only -->
    <script src="<?=Url::base()?>js/demo-rtl.js"></script>
    <!--
    If you need RTL support just include here RTL CSS file <link rel="stylesheet" type="text/css" href="css/libs/bootstrap-rtl.min.css" />
    And add "rtl" class to <body> element - e.g. <body class="rtl">
    -->

    <!-- libraries -->
    <link rel="stylesheet" type="text/css" href="<?=Url::base()?>/css/libs/font-awesome.css" />

    <!-- global styles -->
    <link rel="stylesheet" type="text/css" href="<?=Url::base()?>/css/compiled/theme_styles.css" />

    <!-- this page specific styles -->

    <!-- google font libraries -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300|Titillium+Web:200,300,400' rel='stylesheet' type='text/css'>

    <link type="image/x-icon" href="/images/favicon.ico" rel="shortcut icon"/>

    <!--[if lt IE 9]>
    <script src="<?=Url::base()?>js/html5shiv.js"></script>
    <script src="<?=Url::base()?>js/respond.min.js"></script>
    <![endif]-->
    <?php $this->head() ?>
</head>
<body id="error-page">
<?php $this->beginBody() ?>
<div class="container">
    <?=$content?>
</div>

<!-- global scripts -->
<script src="<?=Url::base()?>/js/jquery.js"></script>
<script src="<?=Url::base()?>/js/bootstrap.js"></script>

<!-- this page specific scripts -->


<!-- theme scripts -->
<script src="<?=Url::base()?>/js/scripts.js"></script>

<!-- this page specific inline scripts -->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>