backend/models/User.php
<?php
/**
 * Created by PhpStorm.
 * User: buba
 * Date: 09.04.15
 * Time: 19:32
 */

namespace backend\models;


class User extends \common\models\User{

    /**
     * @inheritdoc
     */
    public static function find()
    {
        return parent::find()->andWhere(['role'=>[self::ROLE_MODERATOR,self::ROLE_ADMIN]])->one();
    }


}

common/models/User.php
<?php
namespace common\models;

use console\migrations\Migration;
use Yii;
use yii\base\NotSupportedException;
use yii\web\BadRequestHttpException;
use yii\web\ForbiddenHttpException;
use yii\web\IdentityInterface;

use common\interfaces\IStatus;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property integer $role
 * @property string $email_confirmation_token
 * @property string $auth_key
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $password write-only password
 *
 * @property Profile $profile
 */
abstract class User extends ActiveRecord implements IdentityInterface,IStatus
{


    const ROLE_USER  = 1;
    const ROLE_DESIGNER  = 2;
    const ROLE_QA = 4;
    const ROLE_DEVELOPER = 8;
    const ROLE_PM = 16;
    const ROLE_ADMIN = 32;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return Migration::TABLE_USER;
    }

    public static function statusList()
    {
        return [
            self::STATUS_DELETED => [ 'text'=>'Deleted', 'class'=>'label-default', 'suffix'=>'default'],
            self::STATUS_PENDING => [ 'text'=>'Pending', 'class'=>'label-warning', 'suffix'=>'warning'],
            self::STATUS_ACTIVE => [ 'text'=>'Active', 'class'=>'label-success', 'suffix'=>'success'],
            self::STATUS_BANED => [ 'text'=>'Baned', 'class'=>'label-danger', 'suffix'=>'danger'],
        ];
    }

    /**
     * @return string
     */
    public function getRole()
    {
        switch($this->role){
            case self::ROLE_USER: return 'User';
            case self::ROLE_DESIGNER: return 'Designer';
            case self::ROLE_QA: return 'QA';
            case self::ROLE_DEVELOPER: return 'Developer';
            case self::ROLE_PM: return 'Project Manager';
            case self::ROLE_ADMIN: return 'Admin';
            default: return '';
        }
    }

    /**
     * @return string
     */
    public static function roleList()
    {
        $roles  = [
            self::ROLE_USER => 'User',
            self::ROLE_DESIGNER => 'Designer',
            self::ROLE_QA => 'QA',
            self::ROLE_DEVELOPER => 'Developer',
            self::ROLE_PM => 'Project Manager',
        ];

        if(!Yii::$app->user->isGuest){
            /**@var $user self*/
            $user = Yii::$app->user->identity;
            if($user->role >= self::ROLE_ADMIN){
                $roles[self::ROLE_ADMIN] = 'Admin';
            }
        }
        return $roles;
    }

    /**
     * @inheritdoc
     */
    public function setAttribute($name, $value)
    {
        if($name!='id'){
            if(Yii::$app->user->isGuest){
                throw new ForbiddenHttpException();
            }

            /**@var $user self*/
            $user = Yii::$app->user->identity;

            if($user->id != $this->id){
                if($user->role > User::ROLE_PM) {
                    if ($name == 'role') {

                        if ($user->role < self::ROLE_ADMIN && $value == self::ROLE_ADMIN) {
                            throw new ForbiddenHttpException();
                        }

                    } elseif ($name == 'status') {
                        if ($user->role < User::ROLE_PM) {
                            throw new ForbiddenHttpException();
                        }
                    }
                }else{
                    throw new ForbiddenHttpException();
                }

            }else{
                throw new ForbiddenHttpException();
            }
        }

        parent::setAttribute($name, $value);
    }


    /**
     * @return Profile
     */
    public function getProfile(){

        return $this->hasOne(Profile::className(),['user_id'=>'id']);

    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED, self::STATUS_BANED,self::STATUS_PENDING]],
            ['role', 'in', 'range' => [self::ROLE_ADMIN, self::ROLE_PM, self::ROLE_DEVELOPER,self::ROLE_QA,self::ROLE_DESIGNER,self::ROLE_USER]],
        ];
    }


    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
        ]);
    }

    /**
     * Finds user by email confirmation token token
     *
     * @param string $token email confirmation token
     * @return User|null
     */
    public static function findByEmailConfirmationToken($token)
    {
        if (!static::isTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'email_confirmation_token' => $token,
        ]);
    }

    /**
     * Finds out if  token is valid
     *
     * @param string $token
     * @return boolean
     */
    public static function isTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $expire = Yii::$app->params['tokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        return $timestamp + $expire >= time();
    }


    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Generates new email confirmation  token
     */
    public function generateEmailConfirmationToken()
    {
        $this->email_confirmation_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    /**
     * Removes email confirmation reset token
     */
    public function removeEmailConfirmationToken()
    {
        $this->email_confirmation_token = null;
    }

    /**
     *@return boolean whether the message has been sent successfully
     */
    public function sendEmailConfirmation(){
        $this->generateEmailConfirmationToken();
        $this->save();
        return \Yii::$app->mailer->compose('email_confirmation_token_html', ['user' => $this])
            ->setFrom([\Yii::$app->params['supportEmail'] => \Yii::$app->name . ' robot'])
            ->setTo($this->email)
            ->setSubject('Registration on ' . \Yii::$app->name)
            ->send();
    }

    public function isPending()
    {
        return $this->status == self::STATUS_PENDING;
    }

    public function isDeleted()
    {
        return $this->status == self::STATUS_DELETED;
    }

    public function isSuspended()
    {
        return $this->status == self::STATUS_BANED;
    }
}

frontend/models/User.php
<?php
/**
 * Created by PhpStorm.
 * User: buba
 * Date: 09.04.15
 * Time: 19:28
 */

namespace frontend\models;
use common\models\Profile;
use yii\web\ServerErrorHttpException;


/**
 * @property mixed fullName
 */
class User extends \common\models\User{

    public $fullName;

    public function rules()
    {
        return array_merge(parent::rules(),
            [
                [['fullName','status','role'],'safe','on'=>'search']
            ]
        );

    }


    public function getFullName()
    {
        return $this->profile->fullName;
    }


    public function afterSave($insert, $changedAttributes)
    {
        if($insert){
            //welcome message to user
        }
        parent::afterSave($insert, $changedAttributes);
    }

    /**
     * This method is called when the AR object is created and populated with the query result.
     * The default implementation will trigger an [[EVENT_AFTER_FIND]] event.
     * When overriding this method, make sure you call the parent implementation to ensure the
     * event is triggered.
     */
    public function afterFind()
    {
        if($this->profile == null ){
            $profile = new Profile();
            $profile->user_id    = $this->id;
            if(!$profile->save()){
                throw new ServerErrorHttpException('Cannot create profile for user #ID '.$this->id);
            }
        }
    }

    /**
     * @param string $str
     * @return string|null
     */
    public static function parseGender($str){
        if(is_string($str) && !empty($str)){
            return strtoupper(substr($str,0,1));
        }else{
            return null;
        }
    }


}

frontend/models/UserForm.php
<?php
/**
 * Created by PhpStorm.
 * User: buba
 * Date: 7/22/15
 * Time: 12:16 PM
 */

namespace frontend\models;
use common\models\Profile;
use yii\db\Query;

abstract class UserForm extends \yii\base\Model
{
    const USERNAME_PATTERN = '/^\s*[a-z][0-9a-z_]+\s*$/';

    public $id;
    public $username;
    public $email;
    public $password;
    public $confirmPassword;

    //optional fields
    public $firstName ;
    public $lastName ;
    public $gender ;

    public $position;



    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [

            ['id', 'integer'],

            ['username', 'filter', 'filter' =>function($value){return strtolower(trim(strip_tags($value)));}],
            ['username', 'required'],
            ['username', 'match','pattern'=>self::USERNAME_PATTERN,'message'=>'Username should start with a letter and can contain only (a-z,0-9,_)',],
            ['username', 'string', 'min' => 2, 'max' => 10],

            [['firstName','lastName'], 'required'],
            [['firstName','lastName'], 'filter', 'filter' =>function($value){return ucfirst(trim(strip_tags($value)));}],
            [['firstName','lastName'], 'string', 'min' => 2, 'max' => 30],

            ['gender', 'required'],
            ['gender', 'filter', 'filter' =>function($value){return strtoupper(trim(strip_tags($value)));}],
            ['gender','in','range'=>[Profile::GENDER_FEMALE,Profile::GENDER_MALE]],

            ['email', 'filter', 'filter' => 'trim'],
            ['email', 'required'],
            ['email', 'email'],

            ['password','compare','compareAttribute'=>'username','operator'=>'!=','message'=>'You are using your username as password'],
            ['password','compare','compareAttribute'=>'email','operator'=>'!=','message'=>'You are using your email as password'],
            ['password', 'match','pattern'=>'/^(.){8,20}$/'],
            ['password', 'string', 'min' => 8],

            ['confirmPassword','compare','compareAttribute'=>'password','message'=>'You must exactly repeat the password picked  above'],

            ['position','filter','filter'=>function($value){return trim(strip_tags($value));}],
            ['position','required'],
            ['position','string','length'=>[2,30]]
        ];
    }


}

frontend/controllers/UserController.php
<?php
/**
 * Created by PhpStorm.
 * User: buba
 * Date: 27.04.15
 * Time: 20:19
 */

namespace frontend\controllers;


use frontend\models\User;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class UserController extends Controller{


    /**
     * @inheritdoc
     */
    public function init()
    {
        $this->layout = 'main';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],

                ],
            ],
        ];
    }



    public function actionProfile(){

        if($user = User::findByUsername(\Yii::$app->request->get('username'))){
            return $this->render('profile',['user'=>$user]);
        }else{
            throw new NotFoundHttpException();
        }

    }

    public function actionConfirmEmailRequest(){
        /* @var $user \frontend\models\User */
        $user = \Yii::$app->user->identity;
        if($user->sendEmailConfirmation()){
            \Yii::$app->getSession()->setFlash('success', 'Please check your email for confirmation');
        }else{
            \Yii::$app->getSession()->setFlash('danger', 'There was be an error when sending confirmation token');
        }
        return  $this->redirect(\Yii::$app->request->referrer?:'profile');

    }

    public function actionConfirmEmail($token)
    {
        try {
            $user = User::findByEmailConfirmationToken($token);
            if($user){
                $user->removeEmailConfirmationToken();
                $user->save();
                \Yii::$app->getSession()->setFlash('success', 'You successfully confirmed your email address');
                return \Yii::$app->getResponse()->redirect(Url::to(['profile']));
            }else{
                throw new Exception('Wrong email confirmation token');
            }

        } catch (Exception $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
    }
}

frontend/views/user/profile.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $user \frontend\models\User */
$this->title = 'Profile';
\frontend\assets\ProfileAsset::register($this);
$script=<<<INLINE
    $(document).ready(function() {
        $('.conversation-inner').slimScroll({
            height: '340px'
        });
    });

    $(function() {
        $(document).ready(function() {
            $('#newsfeed .story-images').magnificPopup({
                type: 'image',
                delegate: 'a',
                gallery: {
                    enabled: true
                }
            });
        });
    });
INLINE;

$this->registerJs($script);
?>
<div class="row">
    <div class="col-lg-12">

        <div class="row">
            <div class="col-lg-12">

                <h1><?=Yii::$app->user->id == $user->id?'My profile':$user->username.'\' profile'?></h1>
                <?php foreach(Yii::$app->session->getAllFlashes(true) as $key=>$val):?>
                <div class="alert alert-<?=$key?> fade in">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <?=$val?>
                </div>
                <?php endforeach;?>
            </div>
        </div>

        <div class="row" id="user-profile">
            <div class="col-lg-3 col-md-4 col-sm-4">
                <div class="main-box clearfix">
                    <header class="main-box-header clearfix">
                        <h2><?=$user->getFullName()?:$user->username?></h2>
                    </header>

                    <div class="main-box-body clearfix">

                        <img src="<?=$user->profile->getAvatar('medium')?>" alt="" class="profile-img img-responsive center-block" />

                        <div class="profile-label">
                            <span class="label label-default" ><?=$user->getRole()?></span>
                        </div>

                        <div class="profile-label">
                            <span ><?=$user->profile->position?></span>
                        </div>

                        <div class="profile-since">
                            Member since: <?=Yii::$app->formatter->asDate($user->created_at,'php:F d, Y')?>
                        </div>


                        <?php if(null !== $user->email_confirmation_token && Yii::$app->user->id == $user->id):?>
                            <div class="profile-message-btn center-block text-center">
                                <a href="<?=Yii::$app->urlManager->createUrl(['user/confirm-email-request']);?>" >
                                    Confirm your email
                                </a>
                            </div>
                        <?php endif;?>
                    </div>
                </div>

            </div>

            <div class="col-lg-9 col-md-8 col-sm-8">
                <div class="main-box clearfix">
                    <div class="tabs-wrapper profile-tabs">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab-newsfeed" data-toggle="tab">Newsfeed</a></li>
                        </ul>

                        <div class="tab-content">
                            <div class="tab-pane fade in active" id="tab-newsfeed">

                                <div id="newsfeed">
                                    <div class="story">
                                        <div class="story-user">
                                            <a href="#">
                                                <img src="/img/samples/robert-300.jpg" alt=""/>
                                            </a>
                                        </div>

                                        <div class="story-content">
                                            <header class="story-header">
                                                <div class="story-author">
                                                    <a href="#" class="story-author-link">
                                                        Robert Downey Jr.
                                                    </a>
                                                    posted a status update
                                                </div>
                                                <div class="story-time">
                                                    <i class="fa fa-clock-o"></i> just now
                                                </div>
                                            </header>
                                            <div class="story-inner-content">
                                                Now that we know who you are, I know who I am. I'm not a mistake!
                                                It all makes sense! In a comic, you know how you can tell who the
                                                arch-villain's going to be? He's the exact opposite of the hero.
                                                And most times they're friends, like you and me! I should've known
                                                way back when... You know why, David? Because of the kids.
                                                They called me Mr Glass.
                                            </div>
                                            <footer class="story-footer">
                                                <a href="#" class="story-comments-link">
                                                    <i class="fa fa-comment fa-lg"></i> 8320 Comments
                                                </a>
                                                <a href="#" class="story-likes-link">
                                                    <i class="fa fa-heart fa-lg"></i> 82k Likes
                                                </a>
                                            </footer>
                                        </div>
                                    </div>

                                    <div class="story">
                                        <div class="story-user">
                                            <a href="#">
                                                <img src="/img/samples/angelina-300.jpg" alt=""/>
                                            </a>
                                        </div>

                                        <div class="story-content">
                                            <header class="story-header">
                                                <div class="story-author">
                                                    <a href="#" class="story-author-link">
                                                        Angelina Jolie
                                                    </a>
                                                    checked in at <a href="#">Place du Casino</a>
                                                </div>
                                                <div class="story-time">
                                                    <i class="fa fa-clock-o"></i> 3 Minutes ago
                                                </div>
                                            </header>
                                            <div class="story-inner-content">
                                                <div id="map-apple" class="map-content"></div>
                                            </div>
                                            <footer class="story-footer">
                                                <a href="#" class="story-comments-link">
                                                    <i class="fa fa-comment fa-lg"></i> 23k Comments
                                                </a>
                                                <a href="#" class="story-likes-link">
                                                    <i class="fa fa-heart fa-lg"></i> 159k Likes
                                                </a>
                                            </footer>
                                        </div>
                                    </div>

                                    <div class="story">
                                        <div class="story-user">
                                            <a href="#">
                                                <img src="/img/samples/ryan-300.jpg" alt=""/>
                                            </a>
                                        </div>

                                        <div class="story-content">
                                            <header class="story-header">
                                                <div class="story-author">
                                                    <a href="#" class="story-author-link">
                                                        Ryan Gossling
                                                    </a>
                                                    uploaded 5 new photos to album <a href="#">Bora Bora</a>
                                                </div>
                                                <div class="story-time">
                                                    <i class="fa fa-clock-o"></i> 8 Hours ago
                                                </div>
                                            </header>
                                            <div class="story-inner-content">
                                                <div class="story-images clearfix">
                                                    <a href="/img/samples/tahiti-1.jpg" class="story-image-link">
                                                        <img src="/img/samples/tahiti-1.jpg" alt="" class="img-responsive"/>
                                                    </a>
                                                    <a href="/img/samples/tahiti-2.jpg" class="story-image-link story-image-link-small">
                                                        <img src="/img/samples/tahiti-2.jpg" alt="" class="img-responsive"/>
                                                    </a>
                                                    <a href="/img/samples/tahiti-3.jpg" class="story-image-link story-image-link-small">
                                                        <img src="/img/samples/tahiti-3.jpg" alt="" class="img-responsive"/>
                                                    </a>
                                                    <a href="/img/samples/tahiti-3.jpg" class="story-image-link story-image-link-small">
                                                        <img src="/img/samples/tahiti-3.jpg" alt="" class="img-responsive"/>
                                                    </a>
                                                    <a href="/img/samples/tahiti-2.jpg" class="story-image-link story-image-link-small hidden-xs">
                                                        <img src="/img/samples/tahiti-2.jpg" alt="" class="img-responsive"/>
                                                    </a>
                                                </div>
                                            </div>
                                            <footer class="story-footer">
                                                <a href="#" class="story-comments-link">
                                                    <i class="fa fa-comment fa-lg"></i> 46 Comments
                                                </a>
                                                <a href="#" class="story-likes-link">
                                                    <i class="fa fa-heart fa-lg"></i> 823 Likes
                                                </a>
                                            </footer>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>
            </div>


        </div>

    </div>
</div>