backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        /*$model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }*/
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Auth;
use common\models\Calendar;
use common\models\Profile;
use frontend\models\ContactForm;
use frontend\models\UserSettingForm;
use frontend\models\UserSignUpForm;
use frontend\models\User;
use Yii;
use frontend\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\CalendarForm;
use yii\base\InvalidParamException;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\ServerErrorHttpException;
use yii\widgets\ActiveForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'sign-up','login','request-password-reset','index'],
                'rules' => [
                    [
                        'actions' => ['sign-up','login','request-password-reset'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout','index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'onAuthSuccess'],
                'successUrl' => Url::to(['site/index']),
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionHoliday()
    {
        /**@var $user User*/
        $user = Yii::$app->user->identity;

        if($user->role < User::ROLE_ADMIN){
            throw new ForbiddenHttpException();
        }

        $model = new CalendarForm(['scenario'=>'holiday']);
        $model->id = Yii::$app->request->get('edit');

        if($model->id){
            /**@var $calendar Calendar*/
            $calendar = Calendar::findOne(['id'=>$model->id]);
            if(!$calendar){
                throw new NotFoundHttpException();
            }
            $model->attributes = $calendar->attributes;
            $model->start = (new \DateTime($model->start))->format('d-m-Y');
            $model->end = (new \DateTime($model->end))->format('d-m-Y');
        }

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->save()) {
            Yii::$app->getSession()->setFlash('success', $model->id?
                'Your changes are successfully saved':'New holiday has been successfully added');
            return Yii::$app->getResponse()->redirect(['site/holidays']);
        }else if (Yii::$app->request->isPost){
            Yii::$app->getSession()->setFlash('error',  $model->id?
                'We were unable to save changes':'We were unable to add the new holiday');
        }
        return $this->render('holiday',['model'=>$model]);
    }

    /**
     * @param $client \yii\authclient\ClientInterface
     * @return Response | null;
     */
    public function onAuthSuccess($client)
    {
        /**@var $auth \common\models\Auth */

        $attributes = Auth::parseAttributes($client);
        $auth = Auth::find()->where([
            'source' => $client->getId(),
            'source_id' => $attributes['id'],
        ])->one();

        if (Yii::$app->user->isGuest) {
            if ($auth) { // login
                $user = $auth->user;
                Yii::$app->user->login($user);
            } else { // signup
                if (isset($attributes['email'])  && User::find()->where(['email' => $attributes['email']])->exists()) {
                    Yii::$app->getSession()->setFlash('error',
                        Yii::t('app', "User with the same email as in {client} account already exists but isn't linked to it. Login using email first to link it.", ['client' => $client->getTitle()])
                    );
                } else {
                    $attributes['sourceName']   = $client->getId();
                    $attributes['sourceId']     = $attributes['id'];
                    $response = Yii::$app->getResponse();
                    $response->content = Yii::$app->getView()->renderFile(Yii::getAlias('@app/views/site/auth/popup.php'),['attributes'=>$attributes]);
                    return $response;
                }
            }
        } else { // user already logged in
            if (!$auth) { // add auth provider
                $auth = new Auth([
                    'user_id' => Yii::$app->user->id,
                    'source' => $client->getId(),
                    'source_id' => $attributes['id'],
                ]);
                $auth->save();
            }
        }

        return null;

    }

    public function actionLogin()
    {
        $this->layout = 'auth';
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack(['site/index']);
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return Yii::$app->getResponse()->redirect(['site/login']);
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionSignUp()
    {
        $this->layout = 'auth';
        $model = new UserSignUpForm();
        $model->gender = Profile::GENDER_MALE;
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signUp()) {
                if (Yii::$app->user->login($user)) {
                    return $this->goHome();

                }else{
                    return Yii::$app->getResponse()->redirect(['site/login']);
                }
            }
        }

        return $this->render('sign_up', [
            'model' => $model,
        ]);
    }

    public function actionRequestPasswordReset()
    {
        $this->layout = 'auth';
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');
                $model->email = null;

            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword()
    {
        $token = Yii::$app->request->get('token');
        $this->layout = 'auth';
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionVacation()
    {
        /**@var $user User*/
        $user = Yii::$app->user->identity;

        if($user->role <= User::ROLE_USER){
            throw new ForbiddenHttpException();
        }

        $model = new CalendarForm(['scenario'=>'vacation']);
        $model->id = Yii::$app->request->get('edit');


        if($model->id){
            /**@var $calendar Calendar*/
            $calendar = Calendar::findOne(['id'=>$model->id]);
            if(!$calendar){
                throw new NotFoundHttpException();
            }

            if($user->role < User::ROLE_PM){
                throw new ForbiddenHttpException();
            }

            $model->attributes = $calendar->attributes;
            $model->start = (new \DateTime($model->start))->format('d-m-Y');

frontend/controllers/UserController.php
<?php
/**
 * Created by PhpStorm.
 * User: buba
 * Date: 27.04.15
 * Time: 20:19
 */

namespace frontend\controllers;


use frontend\models\User;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class UserController extends Controller{


    /**
     * @inheritdoc
     */
    public function init()
    {
        $this->layout = 'main';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],

                ],
            ],
        ];
    }



    public function actionProfile(){

        if($user = User::findByUsername(\Yii::$app->request->get('username'))){
            return $this->render('profile',['user'=>$user]);
        }else{
            throw new NotFoundHttpException();
        }

    }

    public function actionConfirmEmailRequest(){
        /* @var $user \frontend\models\User */
        $user = \Yii::$app->user->identity;
        if($user->sendEmailConfirmation()){
            \Yii::$app->getSession()->setFlash('success', 'Please check your email for confirmation');
        }else{
            \Yii::$app->getSession()->setFlash('danger', 'There was be an error when sending confirmation token');
        }
        return  $this->redirect(\Yii::$app->request->referrer?:'profile');

    }

    public function actionConfirmEmail($token)
    {
        try {
            $user = User::findByEmailConfirmationToken($token);
            if($user){
                $user->removeEmailConfirmationToken();
                $user->save();
                \Yii::$app->getSession()->setFlash('success', 'You successfully confirmed your email address');
                return \Yii::$app->getResponse()->redirect(Url::to(['profile']));
            }else{
                throw new Exception('Wrong email confirmation token');
            }

        } catch (Exception $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
    }
}

frontend/views/site/about.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/holidays.php
<?php
use frontend\models\User;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $model frontend\models\CalendarForm */
/* @var $dataProvider yii\data\ActiveDataProvider */
\frontend\assets\BaseAsset::register($this);
\frontend\assets\EditableAsset::register($this);
\frontend\assets\IE9Asset::register($this);
$statusList = \yii\helpers\Json::encode(\common\models\Calendar::statusList());
$url = \yii\helpers\Url::to(['site/holidays','update'=>'yes']);
$this->title = 'Holidays | '.Yii::$app->name;
/**@var $user User*/
$user = Yii::$app->user->identity;
?>
<div class="row">
    <div class="col-lg-12">

        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li><a href="<?=\yii\helpers\Url::base()?>">Home</a></li>
                    <li class="active"><span>Holidays</span></li>
                </ol>

                <div class="clearfix">
                    <h1 class="pull-left">Holidays</h1>

                    <?php if ($user->role >= User::ROLE_ADMIN): ?>
                        <div class="pull-right top-page-ui">
                            <a href="<?= \yii\helpers\Url::to(['site/holiday']) ?>" class="btn btn-primary pull-right">
                                <i class="fa fa-plus-circle fa-lg"></i> Add holiday
                            </a>
                        </div>
                    <?php endif ?>

                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="main-box no-header clearfix">
                    <div class="main-box-body clearfix">

                        <?php
                        Pjax::begin(['enablePushState'=>false]);

                        $columns = [
                            [
                                'attribute'   => 'title',
                                'format'      => 'text',
                                'label'       => 'Shor Desc',
                            ],

                            [
                                'attribute'   => 'description',
                                'format'      => 'text',
                            ],

                            [
                                'attribute'   => 'work_days',
                                'label'      => 'Days',
                                'format'      => 'integer',
                            ],

                            [
                                'attribute'   => 'start',
                                'label'      => 'Starts',
                                'format'      => ['date', 'php:F, d'],
                            ],
                            [
                                'attribute'   => 'end',
                                'label'      => 'Ends',
                                'format'      => ['date', 'php:F, d'],
                            ],

                            [
                                'attribute'     => 'status',
                                'format'        => 'raw',
                                'filter'        => \yii\helpers\ArrayHelper::getColumn(\common\models\Calendar::statusList(),'text'),
                                'value' => function (\common\models\Calendar $cal) {
                                    $class  = 'calendar-status editable editable-click label ';
                                    $label  = '';
                                    $status = \common\models\Calendar::statusList()[$cal->status];
                                    $class .= $status['class'];
                                    $label .= $status['text'];
                                    return "<span class= \"{$class}\" data-type=\"select\" data-name=\"status\" data-title=\"Select status\" data-value=\"{$cal->status}\" data-pk=\"{$cal->id}\">{$label}</span>";
                                },
                                'headerOptions' => ['class'=>'text-center'],
                                'contentOptions'=>['class'=>'text-center'],
                            ],
                        ];
                        if($user->role >= User::ROLE_PM) {
                            $script = <<<JS
    $(document).ready(function(){

        var source1 = [],statusList = $statusList;

        $.each(statusList, function(k, v) {
            source1.push({value: parseInt(k), text: v.text});
        });

        $('.calendar-status').editable({
            url:'$url',
            ajaxOptions: {
                type: 'get',
                dataType: 'json'
            },
            send: 'always',
            success: function(response, newValue) {
               if(response.status!='success') return response.msg;
            },
            error: function(response, newValue) {
                if(response.status === 500) {
                    return 'Service unavailable. Please try later.';
                } else {
                    return response.responseText;
                }
            },
            source: source1,
            mode:'inline',
            highlight:false,
            showbuttons:false,
            select2: {
                width: 200
            },
            display: function(value) {
                $(this).removeClass('label-warning')
                .removeClass('label-danger')
                .removeClass('label-success')
                .addClass(statusList[value].class)
                .text(statusList[value].text);
            }
        });
    });

JS;

                            $this->registerJs($script, \yii\web\View::POS_END);
                            $columns[] = [
                                'class'   => '\yii\grid\ActionColumn',
                                'template'=> '{update} {delete}',
                                'buttons' =>[
                                    'delete'=>function ($url, $model, $key) {
                                        $url = \yii\helpers\Url::to(['site/holidays','delete'=>$model->id]);
                                        $html = '
                                                <a href="'.$url.'" class="table-link danger">
                                                    <span class="fa-stack">
                                                        <i class="fa fa-square fa-stack-2x"></i>
                                                        <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                                                    </span>
                                                </a>';
                                        return $html;
                                    },
                                    'update'=>function ($url, $model, $key) {
                                        $url = \yii\helpers\Url::to(['site/holiday','edit'=>$model->id]);
                                        $html = '
                                               <a data-pjax="0" href="'.$url.'" class="table-link">
                                                    <span class="fa-stack">
                                                        <i class="fa fa-square fa-stack-2x"></i>
                                                        <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
                                                    </span>
                                               </a>';
                                        return $html;
                                    },
                                ]
                            ];
                        }


                        echo GridView::widget([
                            'dataProvider'  => $dataProvider,
                            'id'            => 'holidays',
                            'tableOptions'  => ['class'=>'table user-list table-hover'],
                            'options'       => ['class' => 'table-responsive'],
                            'pager'         => ['options'=>['class'=>'pagination pull-right']],
                            'filterModel'   => $model,
                            'columns'       => $columns,
                        ]);
                        Pjax::end();
                        ?>

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

frontend/views/site/vacations.php
<?php
use frontend\models\User;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $model frontend\models\CalendarForm */
/* @var $dataProvider yii\data\ActiveDataProvider */
\frontend\assets\BaseAsset::register($this);
\frontend\assets\EditableAsset::register($this);
\frontend\assets\IE9Asset::register($this);
$statusList = \yii\helpers\Json::encode(\common\models\Calendar::statusList());
$url = \yii\helpers\Url::to(['site/vacations','update'=>'yes']);
$this->title = 'Vacations | '.Yii::$app->name;
/**@var $user User*/
$user = Yii::$app->user->identity;
?>
<div class="row">
    <div class="col-lg-12">

        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li><a href="<?=\yii\helpers\Url::base()?>">Home</a></li>
                    <li class="active"><span>Vacations</span></li>
                </ol>

                <div class="clearfix">
                    <h1 class="pull-left">Vacations</h1>
                    <?php if ($user->role > User::ROLE_USER): ?>
                    <div class="pull-right top-page-ui">
                        <a href="<?=\yii\helpers\Url::to(['site/vacation'])?>" class="btn btn-primary pull-right">
                            <i class="fa fa-plus-circle fa-lg"></i> Add vacation
                        </a>
                    </div>
                    <?php endif ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="main-box no-header clearfix">
                    <div class="main-box-body clearfix">

                        <?php
                        Pjax::begin(['enablePushState'=>false]);

                        $columns = [
                            [
                                'attribute'   => 'username',
                                'format'      => 'Html',
                                'value' => function (\common\models\Calendar $cal) {
                                    return Html::a($cal->user->username?:$cal->user->username,\yii\helpers\Url::to(['user/profile','username'=>$cal->user->username]),['class'=>'']);
                                },
                            ],
                            [
                                'attribute'     => 'status',
                                'format'        => 'raw',
                                'filter'        => \yii\helpers\ArrayHelper::getColumn(\common\models\Calendar::statusList(),'text'),
                                'value' => function (\common\models\Calendar $cal) {
                                    $class  = 'calendar-status editable editable-click label ';
                                    $label  = '';
                                    $status = \common\models\Calendar::statusList()[$cal->status];
                                    $class .= $status['class'];
                                    $label .= $status['text'];
                                    return "<span class= \"{$class}\" data-type=\"select\" data-name=\"status\" data-title=\"Select status\" data-value=\"{$cal->status}\" data-pk=\"{$cal->id}\">{$label}</span>";
                                },
                                'headerOptions' => ['class'=>'text-center'],
                                'contentOptions'=>['class'=>'text-center'],
                            ],

                            [
                                'attribute'   => 'description',
                                'format'      => 'text',
                            ],

                            [
                                'attribute'   => 'work_days',
                                'label'      => 'Days',
                                'format'      => 'integer',
                            ],

                            [
                                'attribute'   => 'start',
                                'label'      => 'Starts at',
                                'format'      => ['date', 'php:m-d-Y'],
                            ],
                            [
                                'attribute'   => 'end',
                                'label'      => 'Ends at',
                                'format'      => ['date', 'php:m-d-Y'],
                            ],
                            [
                                'attribute'   => 'created_at',
                                'label'      => 'Date',
                                'format'      => ['date', 'php:m-d-Y'],
                            ],
                        ];

                        if($user->role >= User::ROLE_PM) {
                            $script = <<<JS
    $(document).ready(function(){

        var source1 = [],statusList = $statusList;

        $.each(statusList, function(k, v) {
            source1.push({value: parseInt(k), text: v.text});
        });

        $('.calendar-status').editable({
            url:'$url',
            ajaxOptions: {
                type: 'get',
                dataType: 'json'
            },
            send: 'always',
            success: function(response, newValue) {
               if(response.status!='success') return response.msg;
            },
            error: function(response, newValue) {
                if(response.status === 500) {
                    return 'Service unavailable. Please try later.';
                } else {
                    return response.responseText;
                }
            },
            source: source1,
            mode:'inline',
            highlight:false,
            showbuttons:false,
            select2: {
                width: 200
            },
            display: function(value) {
                $(this).removeClass('label-warning')
                .removeClass('label-danger')
                .removeClass('label-success')
                .addClass(statusList[value].class)
                .text(statusList[value].text);
            }
        });
    });

JS;

                            $this->registerJs($script, \yii\web\View::POS_END);

                            $columns[] = [
                                'class'   => '\yii\grid\ActionColumn',
                                'template'=> '{update} {delete}',
                                'buttons' =>[
                                    'delete'=>function ($url, $model, $key) {
                                        $url = \yii\helpers\Url::to(['site/vacations','delete'=>$model->id]);
                                        $html = '
                                                <a href="'.$url.'" class="table-link danger">
                                                    <span class="fa-stack">
                                                        <i class="fa fa-square fa-stack-2x"></i>
                                                        <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                                                    </span>
                                                </a>';
                                        return $html;
                                    },
                                    'update'=>function ($url, $model, $key) {
                                        $url = \yii\helpers\Url::to(['site/vacation','edit'=>$model->id]);
                                        $html = '
                                               <a data-pjax="0" href="'.$url.'" class="table-link">
                                                    <span class="fa-stack">
                                                        <i class="fa fa-square fa-stack-2x"></i>
                                                        <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
                                                    </span>
                                               </a>';
                                        return $html;
                                    },
                                ]
                            ];
                        }

                        echo GridView::widget([
                            'dataProvider'  => $dataProvider,
                            'id'            => 'vacations',
                            'tableOptions'  => ['class'=>'table user-list table-hover'],
                            'options'       => ['class' => 'table-responsive'],
                            'pager'         => ['options'=>['class'=>'pagination pull-right']],
                            'filterModel'   => $model,
                            'columns'       => $columns,
                        ]);
                        Pjax::end();
                        ?>

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>